class Cart_Page_Locatore():
    cart_button = "//a[@id='cartur']"
    click_place_order_button = "//button[contains(text(),'Place Order')]"
    path_name = "//input[@id='name']"
    name="Bizu"
    null=" "
    special_character="@$#@#$%%^%%#"
    country_name = "//input[@id='country']"
    Cuntry="Ethiopia"
    city_name = "//input[@id='city']"
    City="Gondar"
    cridit_carde = "//input[@id='card']"
    Card="2346578"
    month = "//input[@id='month']"
    mo_nth="6"
    x="//body/div[@id='orderModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
    year = "//input[@id='year']"
    ye_ar="2000"
    purchase = "//button[contains(text(),'Purchase')]"
    close_button = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
