class Home_Page_Locators():
    Logo="//body/nav[@id='narvbarx']/a[@id='nava']/img[1]"
    samsung_s6="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/img[1]"
    Add_to_cart="//a[contains(text(),'Add to cart')]"
    cart="//a[@id='cartur']"
    sony_xperia="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[6]/div[1]/a[1]/img[1]"
    sony_xperia_name="//td[contains(text(),'Sony xperia z5')]"
    ipone_name="//td[contains(text(),'Iphone 6 32gb')]"
    nokia_lumi="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[2]/div[1]/a[1]/img[1]"
    sumaung_s7="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[4]/div[1]/a[1]/img[1]"
    iphone_6="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[5]/div[1]/a[1]/img[1]"
    sony_vaio_5="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[8]/div[1]/a[1]/img[1]"
    sony_vaio_7="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[2]/div[1]/a[1]/img[1]"
    sony_vaio_7_name="//td[contains(text(),'Sony vaio i7')]"
    sony_vaio_name="//td[contains(text(),'Sony vaio i5')]"
    next_button="//button[@id='next2']"
    assus_full_HD="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[5]/div[1]/a[1]/img[1]"
    Sony_name="//td[contains(text(),'Sony vaio i5')]"
    phone_button="//a[contains(text(),'Phones')]"
    laptop_button="//a[contains(text(),'Laptops')]"
    dell_i7="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[4]/div[1]/a[1]/img[1]"
    dell_i7_name="//td[contains(text(),'Dell i7 8gb')]"
    dell_15="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[5]/div[1]/a[1]/img[1]"
    dell_15_name="//td[contains(text(),'2017 Dell 15.6 Inch')]"
    monitor_button="//a[contains(text(),'Monitors')]"
    makbook_air="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[3]/div[1]/a[1]/img[1]"
    mk_name="//td[contains(text(),'MacBook air')]"
    sumsung_name="//td[contains(text(),'Samsung galaxy s6')]"
    Apple_monitor="//body/div[@id='contcont']/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/img[1]"
    Apple_name="//td[contains(text(),'Apple monitor 24')]"
    Nokia_lumi_delete="//tbody/tr[1]/td[4]/a[1]"
    place_order="//button[contains(text(),'Place Order')]"
    Place_holder_name="//input[@id='name']"
    pleaceholder_name="Bizu"
    place_holder_cuntry="//input[@id='country']"
    country="Israel"
    place_holder_city="//input[@id='city']"
    city="Sheer Sheva "
    creadit_card="//input[@id='card']"
    card="456738943634"
    Month_card="//input[@id='month']"
    month="5"
    year_please_holder="//input[@id='year']"
    year="2020"
    purchase="//button[contains(text(),'Purchase')]"
    close_plaseholder="//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"