class Login_Locator():
    Login = "//a[@id='login2']"
    User_name = "//input[@id='loginusername']"
    Name_filled="Bizu"
    password = "//input[@id='loginpassword']"
    pass_word="123456"
    null=""
    special_character = "@@##@"
    login_button = "//button[contains(text(),'Log in')]"
    close_button = "//body/div[@id='logInModal']/div[1]/div[1]/div[3]/button[1]"
    X_button = "//body/div[@id='logInModal']/div[1]/div[1]/div[1]/button[1]/span[1]"